language: node_js
node_js:
  - 'stable'
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn flow-typed
  - yarn lint
  - yarn test:coverage --runInBand --no-cache
  - yarn test --runInBand --no-cache
  - codecov
cache:
  directories:
    - node_modules
    - flow-typed
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
branch: dev    
